export const APP_UPDATE_NAME = 'APP_UPDATE_NAME'
export const APP_UPDATE_AUTHOR = 'APP_UPDATE_AUTHOR'
export const APP_UPDATE_LOCATION = 'APP_UPDATE_LOCATION'
export const APP_UPDATE_IPAD_MINI_MOBILE_VIEW = 'APP_UPDATE_IPAD_MINI_MOBILE_VIEW'