export const WORKSHOP_BATCH_REQUEST  = 'WORKSHOP_BATCH_REQUEST'
export const WORKSHOP_BATCH_SUCCESS  = 'WORKSHOP_BATCH_SUCCESS'
export const WORKSHOP_BATCH_FAIL  = 'WORKSHOP_BATCH_FAIL'

export const WORKSHOP_INSTRUCTOR_REQUEST = 'WORKSHOP_INSTRUCTOR_REQUEST'
export const WORKSHOP_INSTRUCTOR_SUCCESS = 'WORKSHOP_INSTRUCTOR_SUCCESS'
export const WORKSHOP_INSTRUCTOR_FAIL = 'WORKSHOP_INSTRUCTOR_FAIL'

export const COURSE_GROUP_REQUEST = 'COURSE_GROUP_REQUEST'
export const COURSE_GROUP_SUCCESS = 'COURSE_GROUP_SUCCESS'
export const COURSE_GROUP_FAIL = 'COURSE_GROUP_FAIL'

export const COURSE_GROUP_LIST_REQUEST = 'COURSE_GROUP_LIST_REQUEST'
export const COURSE_GROUP_LIST_SUCCESS = 'COURSE_GROUP_LIST_SUCCESS'
export const COURSE_GROUP_LIST_FAIL = 'COURSE_GROUP_LIST_FAIL'

