export const DASHBOARD_REQUEST = "DASHBOARD_REQUEST";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const DASHBOARD_FAIL = "DASHBOARD_FAIL";

export const DASHBOARD_LEARN_BATCH_REQUEST = "DASHBOARD_LEARN_BATCH_REQUEST";
export const DASHBOARD_LEARN_BATCH_SUCCESS = "DASHBOARD_LEARN_BATCH_SUCCESS";
export const DASHBOARD_LEARN_BATCH_FAIL = "DASHBOARD_LEARN_BATCH_FAIL";

export const DASHBOARD_LEARN_CLASS_REQUEST = "DASHBOARD_LEARN_BATCH_REQUEST";
export const DASHBOARD_LEARN_CLASS_SUCCESS = "DASHBOARD_LEARN_BATCH_SUCCESS";
export const DASHBOARD_LEARN_CLASS_FAIL = "DASHBOARD_LEARN_BATCH_FAIL";

export const DASHBOARD_COURSE_REQUEST = "DASHBOARD_COURSE_REQUEST";
export const DASHBOARD_COURSE_SUCCESS = "DASHBOARD_COURSE_SUCCESS";
export const DASHBOARD_COURSE_FAIL = "DASHBOARD_COURSE_FAIL";

export const DASHBOARD_ACTIVECOURSE_REQUEST = "DASHBOARD_ACTIVECOURSE_REQUEST";
export const DASHBOARD_ACTIVECOURSE_SUCCESS = "DASHBOARD_ACTIVECOURSE_SUCCESS";
export const DASHBOARD_ACTIVECOURSE_FAIL = "DASHBOARD_ACTIVECOURSE_FAIL";

export const JOURNEY_COURSE = "JOURNEY_COURSE";
