export const INSTRUCTOR_INFO_REQUEST  = 'INSTRUCTOR_INFO_REQUEST'
export const INSTRUCTOR_INFO_SUCCESS  = 'INSTRUCTOR_INFO_SUCCESS'
export const INSTRUCTOR_INFO_FAIL  = 'INSTRUCTOR_INFO_FAIL'

export const INSTRUCTOR_SCHEDULE_REQUEST  = 'INSTRUCTOR_SCHEDULE_REQUEST'
export const INSTRUCTOR_SCHEDULE_SUCCESS  = 'INSTRUCTOR_SCHEDULE_SUCCESS'
export const INSTRUCTOR_SCHEDULE_FAIL  = 'INSTRUCTOR_SCHEDULE_FAIL'

export const INSTRUCTOR_BATCH_REQUEST  = 'INSTRUCTOR_BATCH_REQUEST'
export const INSTRUCTOR_BATCH_SUCCESS  = 'INSTRUCTOR_BATCH_SUCCESS'
export const INSTRUCTOR_BATCH_FAIL  = 'INSTRUCTOR_BATCH_FAIL'

export const INSTRUCTOR_UPDATE_REQUEST  = 'INSTRUCTOR_UPDATE_REQUEST'
export const INSTRUCTOR_UPDATE_SUCCESS  = 'INSTRUCTOR_UPDATE_SUCCESS'
export const INSTRUCTOR_UPDATE_FAIL  = 'INSTRUCTOR_UPDATE_FAIL'

export const INSTRUCTOR_UPDATEBATCHCLASS_REQUEST  = 'INSTRUCTOR_UPDATEBATCHCLASS_REQUEST'
export const INSTRUCTOR_UPDATEBATCHCLASS_SUCCESS  = 'INSTRUCTOR_UPDATEBATCHCLASS_SUCCESS'
export const INSTRUCTOR_UPDATEBATCHCLASS_FAIL  = 'INSTRUCTOR_UPDATEBATCHCLASS_FAIL'

export const INSTRUCTOR_CLASSLINK_UPDATE_REQUEST = 'INSTRUCTOR_CLASSLINK_UPDATE_REQUEST'
export const INSTRUCTOR_CLASSLINK_UPDATE_SUCCESS = 'INSTRUCTOR_CLASSLINK_UPDATE_SUCCESS'
export const INSTRUCTOR_CLASSLINK_UPDATE_FAIL = 'INSTRUCTOR_CLASSLINK_UPDATE_FAIL'

export const INSTRUCTOR_NOTE = 'INSTRUCTOR_NOTE'