export const COURSE = 'COURSE'
export const BATCH = 'BATCH'

export const PAYMENT_ORDER_REQUEST = 'PAYMENT_ORDER_REQUEST';
export const PAYMENT_ORDER_SUCCESS = 'PAYMENT_ORDER_SUCCESS';
export const PAYMENT_ORDER_FAIL = 'PAYMENT_ORDER_FAIL';