export const USER_COURSES_REQUEST  = 'USER_COURSES_REQUEST'
export const USER_COURSES_SUCCESS  = 'USER_COURSES_SUCCESS'
export const USER_COURSES_FAIL  = 'USER_COURSES_FAIL'

export const STUDENT_UPDATE_REQUEST  = 'STUDENT_UPDATE_REQUEST'
export const STUDENT_UPDATE_SUCCESS  = 'STUDENT_UPDATE_SUCCESS'
export const STUDENT_UPDATE_FAIL  = 'STUDENT_UPDATE_FAIL'

export const STUDENT_INFO_REQUEST  = 'STUDENT_INFO_REQUEST'
export const STUDENT_INFO_SUCCESS  = 'STUDENT_INFO_SUCCESS'
export const STUDENT_INFO_FAIL  = 'STUDENT_INFO_FAIL'

export const STUDENT_FREEENROLL_REQUEST  = 'STUDENT_FREEENROLL_REQUEST'
export const STUDENT_FREEENROLL_SUCCESS  = 'STUDENT_FREEENROLL_SUCCESS'
export const STUDENT_FREEENROLL_FAIL  = 'STUDENT_FREEENROLL_FAIL'