export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER_FINISH = 'USER_REGISTER_FINISH';

export const USER_MESSAGE_REQUEST  = 'USER_MESSAGE_REQUEST'
export const USER_MESSAGE_SUCCESS  = 'USER_MESSAGE_SUCCESS'
export const USER_MESSAGE_FAIL  = 'USER_MESSAGE_FAIL'

export const USER_CALLBACK_REQUEST  = 'USER_CALLBACK_REQUEST'
export const USER_CALLBACK_SUCCESS  = 'USER_CALLBACK_SUCCESS'
export const USER_CALLBACK_FAIL  = 'USER_CALLBACK_FAIL'