export const USER_LOGIN_REQUEST  = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS  = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL  = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST  = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS  = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL  = 'USER_REGISTER_FAIL'
export const USER_ERROR_RESET = 'USER_ERROR_RESET'

export const USER_WORKSHOP_REGISTER_REQUEST  = 'USER_WORKSHOP_REGISTER_REQUEST'
export const USER_WORKSHOP_REGISTER_SUCCESS  = 'USER_WORKSHOP_REGISTER_SUCCESS'
export const USER_WORKSHOP_REGISTER_FAIL  = 'USER_WORKSHOP_REGISTER_FAIL'

export const USER_SETPASSWORD_REQUEST  = 'USER_SETPASSWORD_REQUEST'
export const USER_SETPASSWORD_SUCCESS  = 'USER_SETPASSWORD_SUCCESS'
export const USER_SETPASSWORD_FAIL  = 'USER_SETPASSWORD_FAIL'

export const USER_FORGOTPASSWORD_REQUEST  = 'USER_FORGOTPASSWORD_REQUEST'
export const USER_FORGOTPASSWORD_SUCCESS  = 'USER_FORGOTPASSWORD_SUCCESS'
export const USER_FORGOTPASSWORD_FAIL  = 'USER_FORGOTPASSWORD_FAIL'

export const USER_UPDATE_REQUEST  = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS  = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL  = 'USER_UPDATE_FAIL'

export const USER_VALIDATE_REQUEST = 'USER_VALIDATE_REQUEST'
export const USER_VALIDATE_SUCCESS = 'USER_VALIDATE_SUCCESS'
export const USER_VALIDATE_FAIL = 'USER_VALIDATE_FAIL'

export const USER_MESSAGE_REQUEST  = 'USER_MESSAGE_REQUEST'
export const USER_MESSAGE_SUCCESS  = 'USER_MESSAGE_SUCCESS'
export const USER_MESSAGE_FAIL  = 'USER_MESSAGE_FAIL'

export const USER_CALLBACK_REQUEST  = 'USER_CALLBACK_REQUEST'
export const USER_CALLBACK_SUCCESS  = 'USER_CALLBACK_SUCCESS'
export const USER_CALLBACK_FAIL  = 'USER_CALLBACK_FAIL'